Model: add method removeTag(Tag) to API
CS2103AUG2017-T12-B1/main pull request #2
Opened 2017-09-23 11:22 UTC by arturs68

Following "Appendix A: Suggested Programming Tasks to Get Started"
To my mind option of removing a tag from the whole address book will be useful.

Docs are supplied and new test method to test tag removal.

2017-10-02 08:53 UTC, namvd2709 requested changes
I would have a test to make sure that no person in the PersonList contains the tag anymore.

2017-10-02 09:44 UTC, arturs68 commented
@namvd2709 , please verify whether my improvement is satisfactory. Thanks for the idea about improving the tests!

2017-10-02 14:27 UTC, namvd2709 commented on src/test/java/seedu/address/model/ModelManagerTest.java
> +                                               .getAddressBook()
I think it would be readable if you leave it on one line, as it also complies with the rest of the code base.

2017-10-02 14:29 UTC, namvd2709 approved these changes

2017-10-04 05:24 UTC, adileyzekmoon approved these changes

2017-10-04 09:03 UTC, merged